DROP TABLE IF EXISTS `answers`;
DROP TABLE IF EXISTS `media`;
DROP TABLE IF EXISTS `questions`;


CREATE TABLE `questions` (
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `text` VARCHAR(150) NOT NULL,
  `points` INT UNSIGNED NOT NULL
);


CREATE TABLE `answers` (
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `text` VARCHAR(150) NOT NULL,
  `correct` BOOLEAN NOT NULL,
  `questionid` INT UNSIGNED NOT NULL,
  FOREIGN KEY (questionid)
    REFERENCES questions (id)
    ON DELETE CASCADE
);


CREATE TABLE `media` (
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `content` MEDIUMBLOB NOT NULL,
  `questionid` INT UNSIGNED NOT NULL,
  FOREIGN KEY (questionid)
    REFERENCES questions (id)
    ON DELETE CASCADE
);
